### ISSUE TITLE
how to use with express and typescript require ?

### ISSUE THREAD

**Issue by agborkowski** [typicode/please-upgrade-node#17]

**Comment by typicode** [comment]
Hi @agborkowski,

It would need some testing, as I don't know if TS changes the order of imports or if the output can be compatible with old Node versions, ...

To make things simpler, personally, I would create an `index.js` with something like this:

```js
// This will work in Node 0.12
const pkg = require('./package.json')
require('please-upgrade-node')(pkg)

// Then require the transpiled TS code
require('./lib/your-server')
```
