### ISSUE TITLE
Feature request: .nvmrc

### ISSUE THREAD

**Issue by ronkorving** [typicode/please-upgrade-node#8]
First of all, great little module. I would very much like to use this.

So, I stopped using the engines field on my projects quite a while ago, in favor of an .nvmrc file with the required Node version in it. A simple `nvm install` or `nvm use` picks that up and understands what version is needed, which I find very useful. Since I don't want to maintain the right Node version number in 2 places (.nvmrc and package.json), I stopped mentioning it in package.json.

It seems like your module could benefit from supporting .nvmrc on top of the engines field in package.json. What do you think?

**Comment by typicode** [comment]
Hi @ronkorving,

Thank you for the suggestion, as a `nvm` user, I can see the benefit. That said, I'd prefer to keep the project simple for the moment and focused just on one source of truth.

That said, it should be possible to use the version in `.nvmrc` like this:

```js
var fs = require('fs')
var version = fs.readFileSync('.nvmrc')
var pleaseUpgradeNode = require('please-upgrade-node')
pleaseUpgradeNode({ engines: { node : ">=" + version } })
```
