### ISSUE TITLE
Semver ranges: use "semver" package

### ISSUE THREAD

**Issue by ronkorving** [typicode/please-upgrade-node#9]
If you were to use the [semver](https://www.npmjs.com/package/semver) package, you could easily have full semver range syntax support.

**Comment by typicode** [comment]
Thank you for the suggestion, `v3.0.2` now uses https://github.com/substack/semver-compare :)

**Comment by a-x-** [comment]
Why your description is not say it?

**Comment by a-x-** [comment]
from readme.md:

> Important: >= is the only operator supported by please-upgrade-node (e.g. >=6, >=6.0, >=6.0.0).
